name: Build NetHunter Kernel for A5 2017

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: 🛠️ تجهيز بيئة العمل
      run: |
        sudo apt update && sudo apt install -y gcc-aarch64-linux-gnu bc bison flex libssl-dev ccache

    - name: 📥 تنزيل الكود المصدري للكيرنل
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: 🏗️ بناء الكيرنل
      run: |
        export ARCH=arm64
        export CROSS_COMPILE=aarch64-linux-gnu-
        make clean && make mrproper
        make a5y17lte_defconfig
        make -j$(nproc)

    - name: 📦 حفظ الكيرنل النهائي
      run: |
        mkdir -p output
        cp arch/arm64/boot/Image.gz-dtb output/

    - name: 📤 رفع الملف الناتج
      uses: actions/upload-artifact@v4
      with:
        name: A5-2017-Nethunter-Kernel
        path: output/Image.gz-dtb
